version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "com.google.errorprone:error_prone_core"
        update-types: ["version-update:semver-major"]
      - dependency-name: "com.uber.nullaway:nullaway"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.junit:junit-bom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.apache.tomcat.embed:tomcat-embed-core"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.mockito:mockito-core"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
