language: java
jdk:
  - openjdk8

before_script:
  - travis/before_script.sh

script: 
  - mvn test javadoc:javadoc -Ptest-output
  - find $HOME/.m2 -name "_remote.repositories" | xargs rm
  - find $HOME/.m2 -name "resolver-status.properties" | xargs rm -f
  
# If building master, Publish to Sonatype
after_success: 
  - travis/after_success.sh

sudo: false

# Cache settings
cache:
  directories:
    - $HOME/.m2/repository
