dist: xenial
language: minimal
sudo: true
services:
  - docker

env:
  global:
    - SERVICE_NAME=async-http-client
    - REVISION=2.8.1-SNAPSHOT
    - secure: unOkMJrcUp3Sf4VJJwHuqBlYuXz/pLOlOXq0UCNc+K9r4W2ffOsKiZ6C5PlsZV1yZsOnRqmZ8QE35D8o/SsgLbNaeBqscGgHDzUfmjqSxOgaBigMOOWPMgpBHji7nGeSZH/0SXJ8JVQDsGAHv4AIO2gd7225hSJ30mcHaqo0BvkGwCgzSAetTEJ9cH9Rz9gQr30gXNSpomtXA9PiZd/I4cpxupG9+XQxm1F7Yjh7FJ05hIbCqQ9/VxcDCz8uspYDdd765yqcjPA9J/ZVnHnDZ2Q0aNqReHX5fhULZU5O+pXgJWrpO40xkVD3kiFYt2g2Z6fqzm4ahq2MJ6AXilBTB3gVrFGe9wIk16n7UqQwulo/AUuZBaEdAZ2uS6ynUJYWhhag1Vbvgg9Olm0B7/ro/HnWqpq3T6rQhnABDPaIp+1VTQSpqz+OfGqyPGYWqX6wzpxxIEbRYuxKDM7bYSgkOMZeUVC4pJ5hL+zQH/by/c1QlzhLK+GeyXfpSOxGxsESWyUxFBJrK3Ykb2cNSAmLqwlYzygEB1jTlGX4P9aIlco0eAGJWiNtpXNwv8TUvN5mA48aIMzd8Q6yF2TdTTuHipj1G0hR1f/m/pSvXcLgTQgo6lW1/aDuxi2UVxUbOTKW4IOOJcSMSaw5uteVpxeF0gxP9rJczozG3zStT3qJXwo=
    - secure: d4Ybkfw+4ZBFUDcqZT8FF35zE4I+90Usiv03c2Jo20ICquznPvub+snIoouJ7HBKFhtF9/N/HWtctyLPPlnTJEIhuUb3hoza4SbOblzrg2ratMIOGaLGzOlIgdCiw3KoUaRmyhzg543jxSIkimWpYuTmF042w1C5NpzmGmXgR+dmm13srFU+MDM7mutmeZRBzJVkZ2y4byimVy9dcfmI/3XN+TxySySExsmaK3vjDdcv5aoGuMwDjEw9YpPVTNUWmcUCi/TfnKvzDCYXdWtOC3dRmr24nfA3SMD5X4+HbGFLsQHKtQARzzm6UVX/SVWZMpV1rJzEzTwfx6cfaJ9UqoMUIACbnqE5aV+2nGyZEIFMNJDNfFETCnHygZDgbNUIFdPTD/jWfGbAAa8gUVEOrVI4k02qk2xQvAe+VsIegFJsgwnNotsJubJPb6yGaOQmw6tXpSBWaB5smc156cGhmRqWtGyXSpF61aXblNQiRVzhSsYIJc2Oj8/GfU08DPAzoIob/FjJuGu8xlvK0bb/uP0RP2zUu7MvxwVUekNIE9F8WLfUxLRP8eJE8gYEcTymXw88ClImEPSpiR/bveu8ErLFTPC1minztd/K3bfZV0mjKk6JdMcD5ufvFWbWUu/0Uxiv4eIAVn8vwE5cI4ZUq8c2KESNDw1K1JeSPhpErNo=
    - secure: LHV8EkUi0Omq4AdTr0x5rgFyvaqusB70oCb+UzthUXacw34rwNFqHb2wF+zu/9z44KbOLcxGEK6/gXkbk6F3llyPMjBGM6cVOPEVSXaktAfS4R2XCE4s/vnE3b++RTahYFLX/+qW/A3IbpLabCPG/c0iA2UeIwZD9KYtC8G2w4ONTLI0TUmiywpl4Ykcr6VWiEbuTfCdmz4ajiuoYlIo/DqDe0Osdlyz+4pcfOOdL5dxvOEsQTzEHrxWfRhbJyA+RJ9QA9We23AKu9iNgFDB6QzEH+GypOBEBb+c9quswSAcJgElGMxPnwtyFOGzTS32Zb9HgESmopwCkR8G43qSKqfIWrAfZf7wVv2UfAqoIKmdi6vtwAqE7rat9GKc9+m11Igc3cb/9wsfL0I1v/l+ZyM0UthvQTbomqQ7HyXHYbCd07v99C4OpktdkcUVtZYKR25piGD5B5wgpQ1WBGuDrEUGStxHsdkRpiJF0pSyeXJ89Tlj9Ug4RtR8IN1DUUNZt+LadznNxQS642l3g3t6jZ4rGpoAw24Y4aRq1yZM9xv9j/89sLm3T7ZFjCri3k81DdHKQ9WDXD2LgxtvqI1mFsewdU/QD5XUiqgDPsICkE/4MkZp9KUjuXS78P4FFWviAbtYhz6qvsjI1M3HcQAP4vtf55GYqRXX5xyjjQcGOHI=
    - secure: qNVsrxukiNeEjmkyDUgmsuFZFxWDlOcM6MyK2gcfkKW+BjoVAxSMbEablL/PWbt/K0qJZbz3GVE0K9b9/eA6slwR00N0rRHHrVVjSKBD+DjAT9+voixNH2cX0uKNbESVRyjoA9MuFsL+4f7J7kv/NtWrfDB/453RXjycdc93q5AulfpMiZtXS0iHgqi5Agi6nYbZPxAywHWwQIlXCEe/CjyNBYBxp6W5CXCGGCOy83tWWjWDnoPT1ordbVUaXOfQB/6npvMgXcEUEdG4fTsE7JAt9yK/NoqGKamJkZKaKouqwTkW8VvZT2EoC3r1gqT5AeV7Q7sw40dlvCrbdYuNR2fT87TzejWPl3OqwfB1Et6PqB9ZHHR8CM4zJqE/ZyJX3WggBBcbwgaMKYXGD2ycFP2qi4TYsQAK7F6MHdRe4XLErNOTJ8Gi5mLY0fVXaYhwINBjhtD20q40ZzQuPSIIsGe4/2PqVqHsYUSieKjrv1/MjiFGPXnZjMm/RrgfUcMpoCfq6XRfp31IYnvL6iLdpTwE4mZBtBfnKf5qR4TGRM/iOkR9iNvWhNjJKpXM4wX/iGbLBGBVUu+3XkG1/bdOYndj2SL+Lhe8QKnBGUWMvE3RuO0hTaQgsTspj0ASEY1bQ5AW5CoFOPImQOwLOLqQT5eIeqtSHXN/Vdo/53Ujkog=
cache:
  directories:
    - build-cache
#=======
#script:
#  - mvn test javadoc:javadoc -Ptest-output
#  - find $HOME/.m2 -name "_remote.repositories" | xargs rm
#  - find $HOME/.m2 -name "resolver-status.properties" | xargs rm -f

# If building master, Publish to Sonatype
#after_success:
#  - travis/after_success.sh
#>>>>>>> cbe39f1befb89ce01ced3f362df0e1f3719c41f8

install:
  - docker-compose -f docker-compose.yml build

script:
  - docker-compose -f docker-compose.yml run ${SERVICE_NAME}

before_cache:
  - docker-compose -f docker-compose.yml run --rm -v `pwd`/build-cache:/app/build-cache
    ${SERVICE_NAME} bash docker-utils.sh save-cache
