dist: xenial
language: minimal
sudo: true
services:
  - docker

env:
  global:
    - SERVICE_NAME=async-http-client
    - REVISION=2.5.3-SNAPSHOT
    - secure: vto8UyM7tMHE4tUwxmYC150orDzrz/6b33m8V6+yh1uHWJmtqhyshsjLKFMmiqkAHz/7jmrgMMlHcnYJ27IyNJsqd4WNQfUjf9nRuizbRKD+yhy7R+IKbgy8bSYizyvQ/4T07sJkOcebzXJigTlOjxpwDfKgBj7vqr5paXrir0Srs0jjgyMxnASFYaBvy2i6wPyPqslkbwHwTapWg3porl/EmSj9rmgHVnPED5CPYraMp+zTHJCpP6xgGn1N3wS+x3sUDZ4MSHeZLXbaSzmIIUBNbYSUjOnEspD0Pi/78G1cl6sW7KiSIAt+H6hoy1+rU6J4RyB8M6pSvNJDlgnYfemG/6onTAXA5n/0+dcs1X2skA3GscOmPoEUuPYyKeQwk2eXK67UC7LNSu1HSAeIxPgwKv4axmFPv/2GJtM70HP28cR35gzyWMMhsxGT7tuKE7W83bEuT/nUzXCWCC80LCOpRRHvfxczUO7bFDE9Be4K/xKtIAJiHZimcvixRoxRojPVSr8DrmeSFA+oGgE6F0hW6cQDynqF7FlmIb+6h3DVPWegQZqi7RP3UHy2qSwj2gAYAydd6FHib7juc8K4xIDdgZ53reCmQL6ULEwKF2unWDxLZ3urqDmhIc3qRH6it9VWdKoNr25EDgKXMVfiGoeKeZBVAl0KtdD6kDgLE9Q=
    - secure: mLmKxZKFaaa98pVHMMcF/XEoXIebrOX7B9ZSLdGeB/2N9PWQnTRRThLrbd2gY1mpxPW+Nu6Nn4M0eh0g0kfYpypaetq7RO8GtNgRDW7qNDTr3q+dcV0+xW2YC+sAhvOnTMu8uz0bHf1y6iQMMvjggU9pyBD9iGtcANn5WXg+UW9cnlvx44MIzpKXt9RzItNpRgTC2/z+j8QL5zjwpMB2xT6EuP7ZFj1xnCQTAZ04qdOmM9Ro7rpvw0zYUIsYuEiyZMIgaGAsaGr00+VpbM9yRQTx7gGjvU6DLs3NfjJrl9ZyaR/vofAGjeV8DBNWBJwL6faq3y091joLIsWv4+tDfh+SZVwbUUhhHZUS0tuqebC0XAQMR5SAfOcO7t7blu9zk3esaeGYWaahQ3Jy1XupvuRQRu9Uj2p5tQTNRrDN9/8l4a9lwdhruDeHUeAwT1UGyx68WhXppWHuHw/Gbt20mo6nspuFPVJ5JrqdYrcfL4dUs+XY2sg4esweivOfrUy7F0noA85/Ol14P2wHyVp4aO+Bc8R+g87MxVlPm+vyW2YJQOi9EYFnPc6YyCu/RbXjvGh6y8izAN6BojeRJ9OJZjRZCG2s9CgL7a75ZOJEQ/ADpnJyhjD6XPlq7ZLwrh0j9fKLTYpk/zh26Ws/ZtGi0sMlwIXotGzVrIQUGgOmS00=
    - secure: DPh5/VR6H3TSzReXgN6HVUoS7nvBX6nchs4esS0jLc/H34wAhC87d8g/8rn7GOvlf/jfr3ujUdl9EFGEy5WjfhNJYDqD/lLz2FmeNh8mI5ZX6mAhmd1CI7ow3miT/Dj/jdY/felWjgWRQIZRaYAv+qwoT96JSSEIO4lpfzafp4lXeD9oKp5t2Uk+Afz41x+e/OCoOW1VtUZi9VEiKbxcQCrwZRuHptTveJCi86zPeIokuUT+BBs0qQur960bq0c+XpkOC6tg3SLIQJJ/OSariiGfuap/A8ZObn9YFprmUYUUV9X8sOPuCBMOMQkqeG9DxNGEloHa9Xi+QpLTfFuLPvyp+PhZVYlMLvsH2GeWLNimlBqENaeKt/2DcO6pwf5TB0JcpV5tEPcjI3QVuqUEk6oXpwwAdoff4bN6Uafo3vKyQXEAsr26b590kxAhKxpI7nPmYtvHSkCfVxLh5Q2R6C0dpaGdamBRKjD+Lku2PJXE+lErk5SnK2BgBkiuuBaxVvUYO9RatucVVne+VDTJY6brcXJEEDs/myfK6lpF2cb5BM14l58iHWBQHmiDhGyl3CKRVXpavG9IuuVMf7siV0957ixCZstlU7J4RDwunGrl6RM3BQdj55atnHu+AKuy3piVy+NX+IimiaRsWw+N04pO3sAakG0fMa1YQ55RDOQ=
    - secure: eZclfJ0N5XzH4Y8ZzLrbcX6iv9Mgc4gctU//jNTN39U2qlBvSUiuY3GDwZfPZjC/V0aeS1+Kb/NBeHaOTfEcqd3+nn4lYrEz3Aqi3NJoapgcWtcQDwIs9edRoJLxZ2iRJJqMY0ONTDur5qgAw+21Pk1KCHFMYVwHcXuOqf5fGTxhi0m1qSEHXJUNnVHP9mAwcF9YvmePeBi/s9RU/E6vHjjg7ZH//JTnGYERn9EqygXwFP+BKx+HrI+8mzmgOiZvwJkUrA6Yk6Z0QIcMiBfIVKm8AdQr4lo8UtZcm1YWz4z0wnN24UxKf3PwKy9Br9Ol2T4nLlAfRYBmNF6HM/nsC+TENfelZvp8xkH79hsdSfCNoWS5Ir1LgvKGJ/Nr/msM80bvBOqsqeT3MaInuWVRfAVhYlFhqUHuVSQf74qbSYXCyMnUR5GYZ6ZY/aYcXw1bFDmBLBRroMw4E76NLsmqoAU8Cq9PaZIqsGGt5fqv5tJMEPaAWr0tNwywtVVoLV3wZh15dClMRkfvrYEUuSBLw0neAHDVNz4UYvySfQgAtDIndxR9lwoBssMGi4zNVfFJ/kAFSTaWoiwu2Q7dp4LJIgG1ZHvUV1uICZhd9rPjEjS83FNCSAt1WBX7r8hLbBLhZBjl7dMl4CQqW4xC6JjzHjACiHGpjoyBBy9arrxg4PU=

cache:
  directories:
    - build-cache

install:
  - docker-compose -f docker-compose.yml build

script:
  - docker-compose -f docker-compose.yml run ${SERVICE_NAME}

before_cache:
  - docker-compose -f docker-compose.yml run --rm -v `pwd`/build-cache:/app/build-cache ${SERVICE_NAME} bash docker-utils.sh save-cache
