name: Build Check

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  Verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Grant Permission
        run: chmod +x ./mvnw
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'
      - name: Verify
        run: ./mvnw clean verify -DskipTests -Dgpg.skip=true

  RunOnLinux:
    runs-on: ubuntu-latest
    needs: Verify
    steps:
      - uses: actions/checkout@v4
      - name: Grant Permission
        run: chmod +x ./mvnw
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'
      - name: Run Tests
        run: ./mvnw -B -ntp test

  RunOnMacOs:
    runs-on: macos-latest
    needs: Verify
    steps:
      - uses: actions/checkout@v4
      - name: Grant Permission
        run: chmod +x ./mvnw
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'
      - name: Run Tests
        run: ./mvnw -B -ntp test

  RunOnWindows:
    runs-on: windows-latest
    needs: Verify
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'
      - name: Run Tests
        run: ./mvnw.cmd -B -ntp test
