name: Snapshot Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Grant Permission
        run: chmod +x ./mvnw

      - name: Check SNAPSHOT version
        id: check-version
        run: |
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          if [[ "$VERSION" == *-SNAPSHOT ]]; then
            echo "is_snapshot=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_snapshot=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Remove old Maven Settings
        if: steps.check-version.outputs.is_snapshot == 'true'
        run: rm -f /home/runner/.m2/settings.xml

      - name: Maven Settings
        if: steps.check-version.outputs.is_snapshot == 'true'
        uses: s4u/maven-settings-action@v4.0.0
        with:
          servers: |
            [{
              "id": "central",
              "username": "${{ secrets.OSSRH_USERNAME }}",
              "password": "${{ secrets.OSSRH_PASSWORD }}"
            }]

      - name: Deploy Snapshot
        if: steps.check-version.outputs.is_snapshot == 'true'
        run: ./mvnw -B -ntp deploy -DskipTests
